"""No value from a request or an event is ever formatted into SQL.

Some queries are assembled with f-strings, which a static analyser cannot tell
apart from injection, so bandit's B608 is disabled and this test takes its
place. It parses every SQL f-string in the shipped code and requires each
interpolated expression to be one of a reviewed set: a timestamp fragment the
code generates, a column name read from the project's own schema, a list of
bound-parameter placeholders, an event-name constant, or a named local that
was checked at the one place it is allowed.

A new interpolation fails here until someone has looked at where its value
comes from and added it, which is the point. Values belong in parameters.
"""

import ast
import pathlib
import re
import unittest

ROOT = pathlib.Path(__file__).resolve().parent.parent
SQL = re.compile(r"\b(SELECT|INSERT|UPDATE|DELETE|CREATE|DROP|WHERE|FROM|JOIN|"
                 r"GROUP BY|ORDER BY|LIMIT|VALUES|PRAGMA)\b")

# Allowed anywhere: none of these can carry outside input.
GLOBAL = [
    re.compile(r"ts\.\w+"),                       # TsExpr fragments, generated by db.TsExpr
    re.compile(r"sc\[['\"]\w+['\"]\]"),           # sources column names, read from PRAGMA table_info
    re.compile(r"_?marks(\(len\(\w+\)\))?"),      # "?,?,?" placeholder lists
    re.compile(r"[A-Z_]+_EVENT"),                 # module-level event-name constants
]

# Allowed only where each was traced to its source.
PER_FILE = {
    "app/analytics/cards.py": {"clause"},                         # "(username=? AND password=?)" joined
    "app/analytics/contributions.py": {"cols", "key", "table"},   # literals passed by _by_sha's two callers
    "app/analytics/escalation.py": {"','.join(cols)"},            # [sc["ip"]] plus fixed column names
    "app/analytics/payloads.py": {"' AND '.join(where)"},         # fixed "day >= ?" style fragments
    "app/analytics/spikes.py": {"n"},                             # len() of the baseline window
    "app/routers/site.py": {"name"},                              # "country" or a schema column name
    "bin/intel_worker.py": {"asn_sel", "cc_expr", "org_expr",     # built from sc[...] column names
                            "join", "day_of_min", "table"},       # and literal table names
    "prune.py": {"t"},                                            # iterates a fixed tuple of table names
}


def shipped_files():
    for d in ("app", "bin"):
        yield from (ROOT / d).rglob("*.py")
    for f in ("ingest.py", "enrich.py", "prune.py"):
        yield ROOT / f


def interpolations():
    for path in shipped_files():
        rel = path.relative_to(ROOT).as_posix()
        for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
            if not isinstance(node, ast.JoinedStr):
                continue
            literal = "".join(v.value for v in node.values
                              if isinstance(v, ast.Constant) and isinstance(v.value, str))
            if not SQL.search(literal):
                continue
            for v in node.values:
                if isinstance(v, ast.FormattedValue):
                    yield rel, node.lineno, ast.unparse(v.value)


class SqlConstructionTests(unittest.TestCase):
    def test_every_interpolation_is_reviewed(self):
        unreviewed = []
        for rel, line, expr in interpolations():
            if any(p.fullmatch(expr) for p in GLOBAL):
                continue
            if expr in PER_FILE.get(rel, set()):
                continue
            unreviewed.append(f"{rel}:{line}: {{{expr}}}")
        self.assertEqual(unreviewed, [], "SQL f-string interpolates an unreviewed value; "
                         "bind it as a parameter, or trace it and add it to PER_FILE")

    def test_the_allow_list_has_no_dead_entries(self):
        # An entry nobody uses any more is an exemption waiting to be reused.
        seen = {(rel, expr) for rel, _line, expr in interpolations()}
        dead = [(rel, e) for rel, exprs in PER_FILE.items() for e in exprs if (rel, e) not in seen]
        self.assertEqual(dead, [])

    def test_the_scan_actually_finds_sql(self):
        self.assertGreater(len(list(interpolations())), 30)
